menu:
- {name: 'Blog', loc: 'internal', url: '/blog'}
- {name: 'CVEs', loc: 'internal', url: '/cve'}
- {name: 'Press', loc: 'internal', url: '/press'}
- {name: 'Resume', loc: 'external', url: 'https://shehzade.s3.amazonaws.com/Abdullah+Ansari+-+Professional+R%C3%A9sum%C3%A9.pdf'}
social:
- {icon: 'github', category: "fab", link: 'https://github.com/shehzade'}
- {icon: 'twitter', category: "fab", link: 'https://twitter.com/shehzade1618'}
- {icon: 'linkedin', category: "fab", link: 'https://www.linkedin.com/in/abdullahansari0'}
- {icon: 'rss', category: "fas", link: '/feed.xml'}

#- {icon: 'HackerOne', link: 'https://hackerone.com/shehzade'}
#- {icon: 'BugCrowd', link: 'https://bugcrowd.com/shehzade'}
